#oc_platform_homepage:
#    path:     /
#    defaults: { _controller: OCPlatformBundle:Default:index }

oc_advert_index:
    path:       /{_locale}/advert/{page}
    defaults: { _controller: OCPlatformBundle:Advert:index, page:1  }
    requirements:
        page:  '\d+'
        _locale: en|fr|de # les locales disponibles, séparées par des pipes « | »

#oc_advert_slug:
#    path:       /advert/view/{year}/{slug}.{_format}
#    defaults: { _controller: OCPlatformBundle:Advert:viewSlug, slug:toto }
#    requirements:
#        year:  '\d+'
#        _format: html|xml

oc_advert_view:
    path:       /{_locale}/advert/view/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view }
    requirements:
        id:  '\d+'
        _locale: en|fr|de # les locales disponibles, séparées par des pipes « | »

oc_advert_add:
    path:       /{_locale}/advert/add/
    defaults: { _controller: OCPlatformBundle:Advert:add }
    requirements:
        _locale: en|fr|de # les locales disponibles, séparées par des pipes « | »

oc_advert_del:
    path:       /{_locale}/advert/del/{id}
    defaults: { _controller: OCPlatformBundle:Advert:del }
    requirements:
        id:  '\d+'
        _locale: en|fr|de # les locales disponibles, séparées par des pipes « | »

oc_advert_edit:
    path:       /{_locale}/advert/edit/{id}
    defaults: { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        id:  '\d+'
        _locale: en|fr|de # les locales disponibles, séparées par des pipes « | »

oc_advert_purge:
    path:   /{_locale}/advert/platform/purge/{days}
    defaults: { _controller: OCPlatformBundle:Advert:purge }
    requirements:
        days:  '\d+'
        _locale: en|fr|de # les locales disponibles, séparées par des pipes « | »

oc_advert_validator:
    path:   /{_locale}/advert/validator/
    defaults: { _controller: OCPlatformBundle:Advert:validator }
    requirements:
        _locale: en|fr|de # les locales disponibles, séparées par des pipes « | »

oc_platform_paramconverter:
  path: /test/{json}
  defaults:
    _controller: "OCPlatformBundle:Advert:ParamConverter"