<?php

namespace OC\PlatformBundle\Entity;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('app');

        $qb->setMaxResults($limit)
            ->leftJoin('app.advert', 'adv')
            ->addSelect('adv')
            ->orderBy('app.date', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;

    }
}
